---
- name: Deploy backend service to EC2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Task 1 - Copy JAR from local to WSL
      ansible.builtin.copy:
        src: "/mnt/d/OneDrive/Escritorio/proyecto/backend/touruguay/target/touruguay-0.0.1-SNAPSHOT.jar"
        dest: "/home/michael/"
      become: no

    - name: Task 2 - Wait for JAR to be copied to WSL
      wait_for:
        path: "/home/michael/touruguay-0.0.1-SNAPSHOT.jar"
        state: present
      timeout: 1800

- name: Deploy and start backend service on EC2
  hosts: EC2
  gather_facts: false

  tasks:
    - name: Task 3 - Stop backend service on EC2
      ansible.builtin.command:
        cmd: "sudo systemctl stop backend.service"
      register: stop_result

    - name: Task 4 - Copy JAR from WSL to EC2
      ansible.builtin.copy:
        src: "/home/michael/touruguay-0.0.1-SNAPSHOT.jar"
        dest: "/home/ubuntu/"
      become: yes
      when: jar_generated.elapsed | default(0) < 1800 and stop_result.changed

    - name: Task 5 - Start backend service on EC2
      ansible.builtin.command:
        cmd: "sudo systemctl start backend.service"
      async: 600
      poll: 0
      ignore_errors: true
      register: start_result
      when: jar_generated.elapsed | default(0) < 1800 and stop_result.changed

    - name: Task 6 - Wait for service start to finish
      async_status:
        jid: "{{ ansible_job_id }}"
      until: async_status.finished
      retries: 60
      delay: 10
      when: jar_generated.elapsed | default(0) < 1800 and stop_result.changed

    - name: Task 7 - Check service status
      ansible.builtin.command:
        cmd: "sudo systemctl status backend.service"
      register: status_result
      until: status_result.rc == 0
      retries: 10
      delay: 5
      when: jar_generated.elapsed | default(0) < 1800 and stop_result.changed
