---
- name: Deploy and sync front-end to S3
  hosts:
    - localhost
  gather_facts: false

  tasks:
    - name: Building del proyecto en Vite
      command: npm run build
      args:
        chdir: /mnt/d/OneDrive/Escritorio/proyecto/frontend/

    - name: Check if 'dist' directory exists
      stat:
        path: /mnt/d/OneDrive/Escritorio/proyecto/frontend/dist
      register: build_directory

    - name: Sync to S3
      when: build_directory.stat.exists
      community.aws.s3_sync:
        bucket: "1023c12-grupo2"
        file_root: "/mnt/d/OneDrive/Escritorio/proyecto/frontend/dist/"        
        region: "us-east-1"
      register: s3_sync_result

    - name: Print S3 sync result
      debug:
        var: s3_sync_result
